# permissions for end users to edit avalancheapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: avalancheapi-editor-role
rules:
- apiGroups:
  - api-node.onfinality.io
  resources:
  - avalancheapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api-node.onfinality.io
  resources:
  - avalancheapis/status
  verbs:
  - get
